### ISSUE TITLE
moderators can kick-off the project formation from chat

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/rocketchat-lg-slash-commands#12]
- `/cycle launch` can be issued by moderators

**Comment by tannerwelsh** [comment]
Proposal from https://github.com/LearnersGuild/learning-os-software/pull/45 : `/cycle launch`

Another idea is: `/cycle practice`, which is more consistent with the state, but less fun. Thoughts @jeffreywescott?

**Comment by jeffreywescott** [comment]
I don't think we need to expose our internal states to the end-user(s), so I'd say go with your gut on what's the best from a UX perspective. Behind the scenes, we'll just map words to states.

**Comment by tannerwelsh** [comment]
Thanks @jeffreywescott. Let's go with `/cycle launch`.

Since this is only a moderator-facing command anyway, the cost to change is a lot lower than learner-facing commands.

**Comment by jeffreywescott** [comment]
Great. Unblocked!
