### ISSUE TITLE
`/vote` command should reply with help message when appropriate

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/rocketchat-lg-slash-commands#13]
## Display Help Message When
- issuing `/vote` with no arguments
- issuing `/vote` with bad arguments

**Comment by tannerwelsh** [comment]
With no arguments (display default help message):

```
> /vote
> COMMAND
    /vote <goalId> <goalId>
  DESCRIPTION
    Vote on goals for the upcoming cycle. Each learner gets two votes per cycle.

    Voting multiple times will override previous votes.
  ARGUMENTS
    goalId : The issue number of a goal (from the goal library)
  USAGE
    /vote 2 5     // vote for goals 2 and 5
    /vote 6 6     // vote for goal 6 twice
```

With too few arguments:

```
> /vote 2
> Invalid command: not enough votes
  You must have forgotten to enter your second choice!

  Use `/vote -h` to read the docs.
```

With too many arguments:

```
> /vote 2 3 4
> Invalid command: too many votes
  Whoa there! Just 2 votes please.

  Use `/vote -h` to read the docs.
```

With invalid goals:

```
> /vote 2 -21
> Error: goal not found
  We weren't able to find a goal with id `-21`. Make sure to enter the goal id from the goal library _exactly_, without any extra characters.
```

**Comment by tannerwelsh** [comment]
Added UX proposal. Feel free to move to Backlog if you are ok with these, @jeffreywescott.

**Comment by jeffreywescott** [comment]
This seems great, @tannerwelsh. Should the side-panel slide out when `/vote` is issued with no arguments? Currently it does. If it's any help making the decision, it's definitely easier to have it slide-out the panel without regard to what arguments are passed.

**Comment by tannerwelsh** [comment]
Thanks @jeffreywescott. I need to do some more thinking on panel behavior, but my initial thoughts are:
1. Yes, let's open the vote panel whenever any `/vote` command is issued (incl. with args)
2. All panels should _also_ have an icon on the sidebar, so that they can be toggled there as well. No "surprise" panels.

**Comment by jeffreywescott** [comment]
Can-do for vote. However, the "no surprise panels" thing seems unsustainable to me ... we'll quickly run out of space for new tabs in the TabBar on the right. See #14.

**Comment by tannerwelsh** [comment]
Sounds good. Will move panel discussion to #14 and LearnersGuild/learning-os-software#47

**Comment by tannerwelsh** [comment]
See conversation in LearnersGuild/learning-os-software#65 re: using a "response URL" to post async responses to a slash command.

**Comment by tannerwelsh** [comment]
@jeffreywescott my sense is this issue needs to be split in two: one for the help messages for invalid commands (in LearnersGuild/game-cli), the other to handle errors from the game server (here). Is that correct?

**Comment by jeffreywescott** [comment]
I'm not sure what you mean by "invalid commands", @tannerwelsh. Do you mean "invalid options"? I am not sure what you have in mind for changes to `game-cli` ... do you want an attribute in the command descriptor for `usageErrorMessage` or something? Isn't "Invalid option: --xyz" enough?

**Comment by tannerwelsh** [comment]
Sure, let me clarify @jeffreywescott - I'm using the term "invalid command" more broadly, to mean any command issued with incorrect (i.e. not-parseable) options, subcommands, and/or arguments.

This seems to me to sit solidly within the `game-cli`, as it's an error of validation at the interface level. Maybe there's no changes needed, and it already works as intended. I thought it might be useful to have an issue on game-cli that ensures the `/vote` command requires 0 or 2 arguments, and replies with an appropriate message when given anything other than that.

**Comment by jeffreywescott** [comment]
Yeah -- the more I think about it, `game-cli` should, at the very least, ensure that the command + arguments are valid in every form, and that is the responsibility of `game-cli`.

Tracked here: [game-cli/#5](https://github.com/LearnersGuild/game-cli/issues/5)
