### ISSUE TITLE
UX: which flex-panels in chat should be permanent and which should be ephemeral

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/rocketchat-lg-slash-commands#14]
Specifically:
- which commands deserve a permanent "tab button" on the right-hand side
  - what icons should be used
- do we want to _remove_ any of the "standard" Rocket.Chat tab buttons

Related: [learning-os-software/#43](https://github.com/LearnersGuild/learning-os-software/issues/43)

**Comment by tannerwelsh** [comment]
Thanks @jeffreywescott - I want to establish a consistent pattern here and so created issue LearnersGuild/learning-os-software#47

**Comment by jeffreywescott** [comment]
Okay. Should we close this issue?

**Comment by tannerwelsh** [comment]
Yes, let's close it. It doesn't really belong in this repo anyway, right?

**Comment by jeffreywescott** [comment]
Two ways to look at it. I had created the issue in this repository because that's where the work will be done to "make it so". If you think it requires more detailed documentation in the GitBook, that's fine with me. Eventually, whatever you decide will generate one (or more) issues on this repository.

**Comment by tannerwelsh** [comment]
Got it. Will re-open then and leave for future assignment.

**Comment by jeffreywescott** [comment]
Issue moved to [LearnersGuild/echo-chat #40](https://github.com/LearnersGuild/echo-chat/issues/40) via [**ZenHub**](https://www.zenhub.com/)
