### ISSUE TITLE
moderators can use `/cycle` command to kick-off retrospective

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/rocketchat-lg-slash-commands#19]

**Comment by tannerwelsh** [comment]
`/cycle reflect` is the specific command proposed in https://github.com/LearnersGuild/learning-os-software/pull/50. Waiting for review before confirmation...

**Comment by tannerwelsh** [comment]
Updated: `/cycle retro` is the new proposal

**Comment by bundacia** [comment]
PR: #29
