### ISSUE TITLE
set up continuous deployment

### ISSUE THREAD

**Issue by bundacia** [LearnersGuild/rocketchat-lg-slash-commands#21]
It would be nice if merging to master automatically pushed a new version to meteor. We should probably add some tests first.

**Comment by jeffreywescott** [comment]
https://medium.com/@sakulstra/meteor-ci-test-and-deploy-e779b62109a3#.d90bjtbmd

**Comment by bundacia** [comment]
meteor needs to be installed on circleci. I [added a little to the circle.yaml](https://github.com/LearnersGuild/rocketchat-lg-slash-commands/commit/f01345642c09f6c79ea8a88b49650f4c9074e573) based in that medium article you linked to. That seems to install meteor ok, but the login command [hangs](https://circleci.com/gh/LearnersGuild/rocketchat-lg-slash-commands/4).
