### ISSUE TITLE
enable more sophisticated option parsing for Learner Guild / Rocket.Chat `/slash` commands

### ISSUE THREAD

**Issue by jeffreywescott** [LearnersGuild/rocketchat-lg-slash-commands#28]
e.g., [yargs](https://www.npmjs.com/package/yargs)

It's worth noting that in Meteor 1.2 and below, node.js packages can only be used on the server-side. For now, that should be fine, since most of the option parsing we're doing for slash commands is on the server-side of the package. However, it might be worth making the `invoke()` consistent across client and server, so that they both get the same (parsed) arguments. This would require a `Meteor.methods({})` addition on the server side and a `Meteor.call()` to that method on the client side.

**Comment by jeffreywescott** [comment]
@bundacia: I've decided to implement this "in-line" in the slash-commands package for now, but I like the idea we discussed today of extracting this into an npm module once we have to support additional CLIs.

I'm still on the fence about broadcasting the slash commands from the game service as an API response.

**Comment by jeffreywescott** [comment]
@bundacia: On second thought, I am experimenting with a custom NPM module after all. Stay tuned ...

**Comment by bundacia** [comment]
sorry, closed on accident =(
