### ISSUE TITLE
Show custom commands in autocomplete popup

### ISSUE THREAD

**Issue by tannerwelsh** [LearnersGuild/rocketchat-lg-slash-commands#35]
When typing just a forward slash, players should see the commands from `game-cli` in the list of available commands.

In other words, they shouldn't have to start typing the command in order to see the usage message.

**Comment by jeffreywescott** [comment]
Issue moved to [LearnersGuild/echo-chat #10](https://github.com/LearnersGuild/echo-chat/issues/10) via [**ZenHub**](https://www.zenhub.com/)
